apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tuppr

helmCharts:
- name: tuppr
  releaseName: tuppr
  namespace: tuppr
  repo: oci://ghcr.io/home-operations/charts
  version: "0.0.73"
  includeCRDs: true

resources:
- talosupgrade.yaml
- k8supgrade.yaml
