apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
    app.kubernetes.io/name: nut-exporter
  name: nut-exporter-scrape
spec:
  endpoints:
  - port: metrics
    path: /ups_metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: nut-exporter
