apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
    app.kubernetes.io/name: nut-exporter
  name: nut-exporter-scrape
spec:
  endpoints:
  - port: metrics
    path: /ups_metrics
    metricRelabelConfigs:
    - action: replace
      replacement: kubernetes
      targetLabel: ups
    - action: labeldrop
      regex: (pod)
  selector:
    matchLabels:
      app.kubernetes.io/name: nut-exporter
