apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: abs-external
spec:
  hostnames:
    - bookshelf.blunders.dev
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-external
      namespace: envoy-gateway
      sectionName: https
  rules:
    - backendRefs:
      - kind: Service
        name: abs-service
        port: 80
